services:
  db:
    # Utilizamos la imagen oficial de PostgreSQL (versión 15 basada en Alpine por ser más ligera)
    image: postgres:15-alpine
    # Nombre del contenedor para identificarlo fácilmente en Docker Desktop
    container_name: bikesystem-db
    restart: always
    # Mapeo de puertos: "Puerto_en_tu_PC:Puerto_dentro_del_contenedor"
    ports:
      - "127.0.0.1:5432:5432"
    # Variables de entorno que configuran el usuario, contraseña y la base de datos inicial
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin_bikesystem}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?Falta POSTGRES_PASSWORD en .env}
      POSTGRES_DB: ${POSTGRES_DB:-bikesystem_db}
    # Volumen: Esto asegura que los datos NO se borren cuando apagues el contenedor
    volumes:
      - pgdata_bikesystem:/var/lib/postgresql/data

# Declaramos el volumen externo donde se guardará la persistencia de datos
volumes:
  pgdata_bikesystem: